### ISSUE TITLE
Comments in a test block are not indented

### ISSUE THREAD

**Issue by sbellware** [test-bench/test-bench-fixture#2]
Comments inside a test block are not indented to the right of the text given to the `test` method. They're indented to the level of the context.

As a countermeasure, fixture code I'm writing that has an inner `comment` is being written with `context` rather than `test`.

**Comment by sbellware** [comment]
Or maybe this is supposed to be done with block-form assert?

**Comment by ntl** [comment]
Consider the following test code:

```ruby
context "Some Context" do
  comment "Some comment"

  test "Some test" do
    comment "Other comment"
  end
end
```

Given that test titles are printed out _after_ they are evaluated (so that they can be green on pass, red on failure), the output I'd expect to see from running the above test code is this:

```
Some Context
  Some comment
  Other comment
  Some test
```

Does that output match your expectation? I'm trying to make sure I understand the request.

**Comment by ntl** [comment]
This is no longer an issue in the latest release.
